# Generated by Django 4.0.2 on 2022-10-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
