# Generated by Django 4.0.2 on 2022-09-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watch_list',
            new_name='Watchlist',
        ),
    ]
