# Generated by Django 4.0.2 on 2022-09-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auc_catagories_auc_list_watch_list_comments_bids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auc_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='auc_list',
            name='catagory',
        ),
        migrations.DeleteModel(
            name='Auc_catagories',
        ),
        migrations.AddField(
            model_name='auc_list',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='auctions.auc_categories'),
        ),
    ]
