# Generated by Django 4.0.2 on 2022-09-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_bid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='User_Comment',
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='item', to='auctions.bid'),
        ),
    ]
